### ISSUE TITLE
Review file descriptor and nginx worker limits for h

### ISSUE THREAD

**Issue by robertknight** [hypothesis/deployment#141]
We experienced [an incident](https://hypothes-is.slack.com/archives/C074BUPEG/p1602551762014000) earlier today where a small percentage (~0.5-1%) of calls to h were failing and the logs for the h Elastic Beanstalk instances contained many entries like this:

```
Oct 13 02:25:57 h-prod_i-xxx error.log 2020/10/13 01:25:57 [alert] 4715#0: 1024 worker_connections are not enough
```

We had a hypothesis that the problem was caused by WebSocket connections consuming too many nginx worker connections. We've [added metrics](https://github.com/hypothesis/h/pull/6320) to the WebSocket process using New Relic ([dashboard](https://one.newrelic.com/launcher/dashboards.launcher?pane=eyJuZXJkbGV0SWQiOiJkYXNoYm9hcmRzLmRhc2hib2FyZCIsInJlZmVycmVycyI6eyJuZXJkbGV0SWQiOiJucjEtY29yZS5ob21lLXNjcmVlbiJ9LCJlbnRpdHlJZCI6Ik1UTTROVEk0TTN4V1NWcDhSRUZUU0VKUFFWSkVmR1JoT2pVNE5EWTEiLCJ1c2VEZWZhdWx0VGltZVJhbmdlIjpmYWxzZSwiaXNUZW1wbGF0ZUVtcHR5IjpmYWxzZSwic2VsZWN0ZWRQYWdlIjoiTVRNNE5USTRNM3hXU1ZwOFJFRlRTRUpQUVZKRWZERTBOVGMxTWpVIiwiZWRpdE1vZGUiOmZhbHNlLCJpc1NhdmluZ0VkaXRDaGFuZ2VzIjpmYWxzZX0=&platform[$isFallbackTimeRange]=false)) and it seems to bear that finding out as the number of WS connections per instance are quite close to the 1K value.

We'll need to look at tuning the nginx `worker_connections`  limit, max open files limit and possibly other limits to make sure we've got enough headroom.

### A note on upping the limit

 * It's entirely possible that the amount of websocket connections or other work is being determined by this value (we are rejecting other connections)
 * Therefore upping the value dramatically could cause a flood of extra work to the machine
 * For this reason it's probably wise to up the value a small amount at first to see how the system responds (i.e. to 1.5x)
 * If this looks ok, we might then want to open up the throttle a bit

----

### Some notes on how to determine limits.
To find out how many file handles a particular program has open:

* Use `ps aux | grep ...` or `pidof ...` to find out the pids associated with a program
* Use `lsof -p <pid> | wc -l` to see the number of open files (may require sudo)

To find out the limits on the system:

 * `ulimit -Sn` to find out the "soft" limit (1024 on the host machine, 200k in the container)
 * `ulimit -Hn` to find out the "hard" limit (4096 on the host machine, 200k in the container)

The "soft" limit is the one apps with use by default but they can change it themselves up to the "hard" limit which is set by root.

**Comment by robertknight** [comment]
Summary of the issue and proposed fixes from Jon B: https://hypothes-is.slack.com/archives/C074BUPEG/p1602607754049900

**Comment by jon-betts** [comment]
Some things @indigobravo and me discovered while investigating this:

* NGINX connections are shared between connecting to the client and connecting to the resource being proxied
* So a persistent websocket may actually need _two_ connections (one to the client, and one to the WS) to proxy
* It seems there's a bit of disagreement and confusion around this, but as far as we can tell we still need one file descriptor per connection (two per ws connection as outlined above)

This isn't very consistent with what we are seeing though, as this means we shouldn't be able to have the number of connections open we seem to. 

The option to set this is:

 * https://nginx.org/en/docs/ngx_core_module.html#worker_rlimit_nofile - `worker_rlimit_nofile`

This will allow NGINX to allocate itself more handles, up to the hard limit (which is 4096).

**Comment by indigobravo** [comment]
I am going to close this issue. We have implemented an EBextension to increase the NginX worker count. [80_nginx_workers.config](https://github.com/hypothesis/deployment/blob/master/h/ebextensions/prod/80_nginx_workers.config). 

I have taken a look at one of the H hosts, and it is not using more than `650` workers under its current state of load. I have also searched papertrail and I am not seeing any reference to `worker_connections are not enough`. Those logs go back to the start of November.

**Comment by indigobravo** [comment]
To add a little more to this, here is a graph over the last 7 days. We seem to peak around the `1080` mark.
<img width="533" alt="Screenshot 2020-11-18 at 15 09 37" src="https://user-images.githubusercontent.com/18003117/99548173-42679680-29b0-11eb-8dd3-fd8a9980bead.png">
