### ISSUE TITLE
Is there complete documentation for locally deployment?

### ISSUE THREAD

**Issue by fishfree** [hypothesis/deployment#28]
I want to deploy all necessary packages for running a fully functional Hypothesis in a Ubuntu 16.04 or 18.04 box. But all documentations are piecemeal.

**Comment by robertknight** [comment]
Hello,

I'm afraid we don't have comprehensive documentation for creating a production deployment of Hypothesis at present. The scripts in this repository are tailored to our deployment requirements. I believe this documentation is something we will create but I can't promise a timeframe yet.
