### ISSUE TITLE
block remaining ips and domains on via2 hosts

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/deployment#56]
# Problem
Last sprint we blocked the metadata url but there are still some remaining (though less critical) ip addresses to block from being proxied via via2. These are IPs that could give the user undesirable access to host machine information. 

# IPs remaining
* 10.0.0.0/8		        # RFC1918 possible internal network
* 172.16.0.0/12		# RFC1918 possible internal network
* 192.168.0.0/16		# RFC1918 possible internal network
* fc00::/7       	                 # RFC 4193 local private network range
* fe80::/10      	                 # RFC 4291 link-local (directly plugged) machines

**Comment by hmstepanek** [comment]
Reply we decided to just forgo blocking the loopback ip as there's nothing you can really gain by proxying it.

**Comment by dmfine** [comment]
We can't block all 10.x because that would block the gateway. I think everything we're trying to accomplish this is already handled by security groups - We can maybe close this as non-blocking

**Comment by robertknight** [comment]
Can this be closed given the change in direction of the new proxy server? CC @hmstepanek ?
